import type { ThemeDefinition } from "./theme";

export const bloodBowlTheme: ThemeDefinition = {
  name: "bloodbowl",
  tokens: {
    "--bg": "#100d0b",
    "--surface": "#1c1511",
    "--surface-2": "#2a211a",
    "--text-primary": "#f3e7d0",
    "--text-secondary": "#d8c4a1",
    "--text-muted": "#a88f72",
    "--text-inverse": "#16120f",
    "--border": "#71523b",
    "--divider": "#453429",
    "--accent": "#9d171e",
    "--accent-2": "#b78e2c",
    "--accent-3": "#2aa36b",
    "--focus": "#d3ab48",
    "--danger": "#a1181e",
    "--success": "#2aa36b",
    "--input-bg": "#f2e7d2",
    "--input-border": "#b79f7e",
    "--input-text": "#16120f",
    "--placeholder": "#846f56",
    "--btn-bg": "#34271f",
    "--btn-text": "#f2e7d6",
    "--btn-text-muted": "#ccb89d",
    "--btn-border": "#856245",
    "--icon-primary": "var(--text-primary)",
    "--icon-secondary": "var(--text-secondary)",
    "--control-fg": "var(--text-primary)",
    "--control-fg-muted": "var(--text-secondary)",
    "--btn-primary-bg": "linear-gradient(180deg, #b62a33 0%, #8f171f 56%, #6f1219 100%)",
    "--btn-primary-border": "#d08a72",
    "--radius-control": "10px",
    "--radius-panel": "12px",
    "--radius-sheet": "14px",
    "--border-width-strong": "2px",
    "--panel-outline": "1px solid rgba(245, 212, 160, 0.08)",
    "--font-display": '"Cinzel", "Times New Roman", Georgia, serif',
    "--font-ui": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--color-bg": "var(--bg)",
    "--color-surface": "var(--surface)",
    "--color-surface-soft": "var(--surface-2)",
    "--color-surface-muted": "#36281f",
    "--color-surface-weak": "#241a14",
    "--color-text": "var(--text-primary)",
    "--color-text-muted": "var(--text-secondary)",
    "--color-text-subtle": "var(--text-muted)",
    "--color-border": "var(--border)",
    "--color-border-soft": "#916640",
    "--color-border-muted": "#69482e",
    "--color-border-dashed": "#8d663f",
    "--color-divider": "var(--divider)",
    "--color-primary": "var(--accent)",
    "--color-primary-contrast": "#ffefda",
    "--color-primary-soft": "#47261d",
    "--color-danger-border": "#c55851",
    "--color-danger-bg": "#421d1b",
    "--color-warning": "#ddb060",
    "--color-warning-border": "#c79a46",
    "--color-warning-bg": "#3d2d17",
    "--color-text-primary": "var(--text-primary)",
    "--color-text-secondary": "var(--text-secondary)",
    "--color-text-muted-alt": "var(--text-muted)",
    "--color-text-inverse": "var(--text-inverse)",
    "--color-accent": "var(--accent)",
    "--color-accent-2": "var(--accent-2)",
    "--color-focus": "var(--focus)",
    "--color-danger": "var(--danger)",
    "--color-input-bg": "var(--input-bg)",
    "--color-input-text": "var(--input-text)",
    "--color-input-border": "var(--input-border)",
    "--color-input-placeholder": "var(--placeholder)",
    "--color-button-bg": "var(--btn-bg)",
    "--color-button-text": "var(--btn-text)",
    "--color-button-border": "var(--btn-border)",
    "--color-button-secondary-bg": "var(--surface-2)",
    "--color-button-secondary-text": "var(--btn-text)",
    "--color-button-secondary-border": "var(--btn-border)",
    "--color-overlay": "rgba(8, 6, 5, 0.72)",
    "--shadow-modal": "0 16px 36px rgba(0, 0, 0, 0.56)",
    "--shadow-toast": "0 10px 26px rgba(0, 0, 0, 0.54)",
    "--color-surface-inset": "rgba(244, 205, 153, 0.1)",
    "--color-panel-highlight": "rgba(241, 214, 173, 0.08)",
    "--color-panel-shadow": "rgba(0, 0, 0, 0.35)",
    "--font-family-base": "var(--font-ui)",
    "--font-family-mono": "\"Courier New\", Courier, monospace",
  },
};
