import type { ThemeDefinition } from "./theme";

export const bloodBowlTheme: ThemeDefinition = {
  name: "bloodbowl",
  tokens: {
    "--font-display": '"Cinzel", "Times New Roman", Georgia, serif',
    "--font-ui": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--color-bg": "#1a1410",
    "--color-surface": "#221914",
    "--color-surface-soft": "#2c211b",
    "--color-surface-muted": "#362720",
    "--color-surface-weak": "#271d17",
    "--color-text": "#f6e7d3",
    "--color-text-muted": "#d8b68a",
    "--color-text-subtle": "#b99262",
    "--text-primary": "#f6e7d3",
    "--text-secondary": "#d8b68a",
    "--text-muted": "#b99262",
    "--input-bg": "#2c211b",
    "--input-text": "#f6e7d3",
    "--color-border": "#6f4a2a",
    "--color-border-soft": "#825734",
    "--color-border-muted": "#5b3d24",
    "--color-border-dashed": "#7a5534",
    "--color-divider": "#4d3523",
    "--color-primary": "#a30f16",
    "--color-primary-contrast": "#fff3e0",
    "--color-primary-soft": "#3b261b",
    "--color-danger-border": "#b74842",
    "--color-danger-bg": "#3a1918",
    "--color-warning": "#f3b04f",
    "--color-warning-border": "#f0a434",
    "--color-warning-bg": "#3a2b16",
    "--color-text-primary": "#f6e7d3",
    "--color-text-secondary": "#d8b68a",
    "--color-text-muted-alt": "#b99262",
    "--color-text-inverse": "#1c130d",
    "--color-accent": "#a30f16",
    "--color-accent-2": "#b88a3b",
    "--color-focus": "#e0b56c",
    "--color-danger": "#d84f48",
    "--color-input-bg": "#efe3c5",
    "--color-input-text": "#2e2215",
    "--color-input-border": "#a07a4b",
    "--color-input-placeholder": "#6e5840",
    "--color-button-bg": "#a30f16",
    "--color-button-text": "#fff3e0",
    "--color-button-border": "#a30f16",
    "--color-button-secondary-bg": "#2c211b",
    "--color-button-secondary-text": "#f6e7d3",
    "--color-button-secondary-border": "#6f4a2a",
    "--color-overlay": "rgba(0, 0, 0, 0.65)",
    "--shadow-modal": "0 12px 32px rgba(0, 0, 0, 0.45)",
    "--shadow-toast": "0 10px 24px rgba(0, 0, 0, 0.5)",
    "--font-family-base": "var(--font-ui)",
    "--font-family-mono": "\"Courier New\", Courier, monospace",
  },
};
