import type { ThemeDefinition } from "./theme";

export const minimalDarkTheme: ThemeDefinition = {
  name: "minimal-dark",
  tokens: {
    "--bg": "#121212",
    "--surface": "#1e1e1e",
    "--surface-2": "#2a2a2a",
    "--text-primary": "#f5f5f5",
    "--text-secondary": "#cfcfcf",
    "--text-muted": "#9a9a9a",
    "--border": "#3a3a3a",
    "--divider": "#2f2f2f",
    "--accent": "#4d90fe",
    "--danger": "#ff5c5c",
    "--success": "#34c759",
    "--input-bg": "#1f1f1f",
    "--input-text": "#f5f5f5",
    "--input-border": "#444",
    "--placeholder": "#8e8e93",
    "--btn-bg": "#2c2c2e",
    "--btn-text": "#f5f5f5",
    "--btn-border": "#444",
    "--focus": "#4d90fe",
    "--font-display": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--font-ui": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--color-bg": "var(--bg)",
    "--color-surface": "var(--surface)",
    "--color-surface-soft": "var(--surface-2)",
    "--color-surface-muted": "#262626",
    "--color-surface-weak": "#232323",
    "--color-text": "var(--text-primary)",
    "--color-text-muted": "var(--text-secondary)",
    "--color-text-subtle": "var(--text-muted)",
    "--color-border": "var(--border)",
    "--color-border-soft": "#444444",
    "--color-border-muted": "#333333",
    "--color-border-dashed": "#4a4a4a",
    "--color-divider": "var(--divider)",
    "--color-primary": "var(--accent)",
    "--color-primary-contrast": "#ffffff",
    "--color-primary-soft": "#1a2f52",
    "--color-danger-border": "#7f2d2d",
    "--color-danger-bg": "#3b1f1f",
    "--color-warning": "#f2c06c",
    "--color-warning-border": "#d9a655",
    "--color-warning-bg": "#3a2f1b",
    "--color-text-primary": "var(--text-primary)",
    "--color-text-secondary": "var(--text-secondary)",
    "--color-text-muted-alt": "var(--text-muted)",
    "--color-text-inverse": "#111827",
    "--color-accent": "var(--accent)",
    "--color-accent-2": "#7ab0ff",
    "--color-focus": "var(--focus)",
    "--color-danger": "var(--danger)",
    "--color-input-bg": "var(--input-bg)",
    "--color-input-text": "var(--input-text)",
    "--color-input-border": "var(--input-border)",
    "--color-input-placeholder": "var(--placeholder)",
    "--color-button-bg": "var(--btn-bg)",
    "--color-button-text": "var(--btn-text)",
    "--color-button-border": "var(--btn-border)",
    "--color-button-secondary-bg": "var(--surface-2)",
    "--color-button-secondary-text": "#f5f5f5",
    "--color-button-secondary-border": "#444444",
    "--color-overlay": "rgba(0, 0, 0, 0.65)",
    "--shadow-modal": "0 10px 30px rgba(0, 0, 0, 0.45)",
    "--shadow-toast": "0 10px 24px rgba(0, 0, 0, 0.4)",
    "--color-surface-inset": "rgba(255, 255, 255, 0.02)",
    "--color-panel-highlight": "rgba(241, 214, 173, 0.08)",
    "--color-panel-shadow": "rgba(0, 0, 0, 0.35)",
    "--font-family-base": "var(--font-ui)",
    "--font-family-mono": 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
};
