import type { ThemeDefinition } from "./theme";

export const minimalDarkTheme: ThemeDefinition = {
  name: "minimal-dark",
  tokens: {
    "--bg": "#121212",
    "--surface": "#1c1c1e",
    "--surface-2": "#2a2a2d",
    "--text-primary": "#f2f2f2",
    "--text-secondary": "#c7c7cc",
    "--text-muted": "#8e8e93",
    "--border": "#3a3a3c",
    "--divider": "#2c2c2e",
    "--accent": "#5f789f",
    "--danger": "#ff5c5c",
    "--success": "#34c759",
    "--input-bg": "#1c1c1e",
    "--input-text": "#f2f2f2",
    "--input-border": "#3f3f42",
    "--placeholder": "#8e8e93",
    "--btn-bg": "#303033",
    "--btn-text": "#f2f2f2",
    "--btn-text-muted": "#b9b9be",
    "--btn-border": "#4a4a4d",
    "--icon-primary": "var(--text-primary)",
    "--icon-secondary": "var(--text-secondary)",
    "--control-fg": "var(--text-primary)",
    "--control-fg-muted": "var(--text-secondary)",
    "--focus": "#5b8fd6",
    "--font-display": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--font-ui": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--color-bg": "var(--bg)",
    "--color-surface": "var(--surface)",
    "--color-surface-soft": "var(--surface-2)",
    "--color-surface-muted": "#242426",
    "--color-surface-weak": "#202022",
    "--color-text": "var(--text-primary)",
    "--color-text-muted": "var(--text-secondary)",
    "--color-text-subtle": "var(--text-muted)",
    "--color-border": "var(--border)",
    "--color-border-soft": "#454548",
    "--color-border-muted": "#2f2f31",
    "--color-border-dashed": "#4e4e52",
    "--color-divider": "var(--divider)",
    "--color-primary": "var(--accent)",
    "--color-primary-contrast": "#ffffff",
    "--color-primary-soft": "#2a3342",
    "--color-danger-border": "#7f2d2d",
    "--color-danger-bg": "#3b1f1f",
    "--color-warning": "#f2c06c",
    "--color-warning-border": "#d9a655",
    "--color-warning-bg": "#3a2f1b",
    "--color-text-primary": "var(--text-primary)",
    "--color-text-secondary": "var(--text-secondary)",
    "--color-text-muted-alt": "var(--text-muted)",
    "--color-text-inverse": "#111827",
    "--color-accent": "var(--accent)",
    "--color-accent-2": "#89a1c2",
    "--color-focus": "var(--focus)",
    "--color-danger": "var(--danger)",
    "--color-input-bg": "var(--input-bg)",
    "--color-input-text": "var(--input-text)",
    "--color-input-border": "var(--input-border)",
    "--color-input-placeholder": "var(--placeholder)",
    "--color-button-bg": "var(--btn-bg)",
    "--color-button-text": "var(--btn-text)",
    "--color-button-border": "var(--btn-border)",
    "--color-button-secondary-bg": "#262629",
    "--color-button-secondary-text": "#f2f2f2",
    "--color-button-secondary-border": "#454548",
    "--interactive-active-bg": "#343438",
    "--interactive-active-border": "#5f789f",
    "--interactive-active-text": "#f2f2f2",
    "--interactive-active-ghost-text": "#c7d5ea",
    "--color-overlay": "rgba(0, 0, 0, 0.65)",
    "--shadow-modal": "0 10px 30px rgba(0, 0, 0, 0.45)",
    "--shadow-toast": "0 10px 24px rgba(0, 0, 0, 0.4)",
    "--color-surface-inset": "rgba(255, 255, 255, 0.02)",
    "--color-panel-highlight": "rgba(241, 214, 173, 0.08)",
    "--color-panel-shadow": "rgba(0, 0, 0, 0.35)",
    "--font-family-base": "var(--font-ui)",
    "--font-family-mono": 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
};
