import type { ThemeDefinition } from "./theme";

export const minimalTheme: ThemeDefinition = {
  name: "minimal",
  tokens: {
    "--font-display": '"Cinzel", "Times New Roman", Georgia, serif',
    "--font-ui": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--color-bg": "#ffffff",
    "--color-surface": "#ffffff",
    "--color-surface-soft": "#fafafa",
    "--color-surface-muted": "#f5f5f5",
    "--color-surface-weak": "#fcfcfc",
    "--color-text": "#111827",
    "--color-text-muted": "#6b7280",
    "--color-text-subtle": "#9ca3af",
    "--color-border": "#dddddd",
    "--color-border-soft": "#eeeeee",
    "--color-border-muted": "#f0f0f0",
    "--color-border-dashed": "#e1e1e1",
    "--color-divider": "#ececec",
    "--color-primary": "#111111",
    "--color-primary-contrast": "#ffffff",
    "--color-primary-soft": "#f9fafb",
    "--color-danger-border": "#f1c4c4",
    "--color-danger-bg": "#fff5f5",
    "--color-warning": "#b45309",
    "--color-warning-border": "#ffc107",
    "--color-warning-bg": "#fff8e1",
    "--color-text-primary": "#111827",
    "--color-text-secondary": "#6b7280",
    "--color-text-muted-alt": "#9ca3af",
    "--color-text-inverse": "#ffffff",
    "--color-accent": "#111111",
    "--color-accent-2": "#b45309",
    "--color-focus": "#2563eb",
    "--color-danger": "#b91c1c",
    "--color-input-bg": "#ffffff",
    "--color-input-text": "#111827",
    "--color-input-border": "#dddddd",
    "--color-input-placeholder": "#9ca3af",
    "--color-button-bg": "#111111",
    "--color-button-text": "#ffffff",
    "--color-button-border": "#111111",
    "--color-button-secondary-bg": "#fafafa",
    "--color-button-secondary-text": "#111111",
    "--color-button-secondary-border": "#dddddd",
    "--color-overlay": "rgba(0, 0, 0, 0.5)",
    "--shadow-modal": "0 10px 30px rgba(0, 0, 0, 0.25)",
    "--shadow-toast": "0 10px 24px rgba(17, 24, 39, 0.16)",
    "--font-family-base": "var(--font-ui)",
    "--font-family-mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
  },
};
