import type { ThemeDefinition } from "./theme";

export const minimalDarkTheme: ThemeDefinition = {
  name: "minimal-dark",
  tokens: {
    "--font-display": '"Cinzel", "Times New Roman", Georgia, serif',
    "--font-ui": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--color-bg": "#121212",
    "--color-surface": "#1e1e1e",
    "--color-surface-soft": "#2a2a2a",
    "--color-surface-muted": "#262626",
    "--color-surface-weak": "#232323",
    "--color-text": "#f5f5f5",
    "--color-text-muted": "#cfcfcf",
    "--color-text-subtle": "#9a9a9a",
    "--text-primary": "#f5f5f5",
    "--text-secondary": "#cfcfcf",
    "--text-muted": "#9a9a9a",
    "--input-bg": "#1f1f1f",
    "--input-text": "#f5f5f5",
    "--color-border": "#3a3a3a",
    "--color-border-soft": "#444444",
    "--color-border-muted": "#333333",
    "--color-border-dashed": "#4a4a4a",
    "--color-divider": "#363636",
    "--color-primary": "#4d90fe",
    "--color-primary-contrast": "#ffffff",
    "--color-primary-soft": "#1a2f52",
    "--color-danger-border": "#7f2d2d",
    "--color-danger-bg": "#3b1f1f",
    "--color-warning": "#f2c06c",
    "--color-warning-border": "#d9a655",
    "--color-warning-bg": "#3a2f1b",
    "--color-text-primary": "#f5f5f5",
    "--color-text-secondary": "#cfcfcf",
    "--color-text-muted-alt": "#9a9a9a",
    "--color-text-inverse": "#111827",
    "--color-accent": "#4d90fe",
    "--color-accent-2": "#7ab0ff",
    "--color-focus": "#4d90fe",
    "--color-danger": "#ef6363",
    "--color-input-bg": "#1f1f1f",
    "--color-input-text": "#f5f5f5",
    "--color-input-border": "#444",
    "--color-input-placeholder": "#8e8e93",
    "--color-button-bg": "#4d90fe",
    "--color-button-text": "#ffffff",
    "--color-button-border": "#4d90fe",
    "--color-button-secondary-bg": "#2a2a2a",
    "--color-button-secondary-text": "#f5f5f5",
    "--color-button-secondary-border": "#444444",
    "--color-overlay": "rgba(0, 0, 0, 0.65)",
    "--shadow-modal": "0 10px 30px rgba(0, 0, 0, 0.45)",
    "--shadow-toast": "0 10px 24px rgba(0, 0, 0, 0.4)",
    "--font-family-base": "var(--font-ui)",
    "--font-family-mono": 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
};
