import type { ThemeDefinition } from "./theme";

export const minimalTheme: ThemeDefinition = {
  name: "minimal-light",
  tokens: {
    "--bg": "#ffffff",
    "--surface": "#ffffff",
    "--surface-2": "#fafafa",
    "--text-primary": "#111827",
    "--text-secondary": "#374151",
    "--text-muted": "#6b7280",
    "--border": "#dddddd",
    "--divider": "#ececec",
    "--accent": "#111111",
    "--danger": "#b91c1c",
    "--success": "#16a34a",
    "--input-bg": "#ffffff",
    "--input-text": "#111827",
    "--input-border": "#dddddd",
    "--placeholder": "#9ca3af",
    "--btn-bg": "#111111",
    "--btn-text": "#ffffff",
    "--btn-border": "#111111",
    "--focus": "#2563eb",
    "--font-display": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--font-ui": "system-ui, -apple-system, Segoe UI, Roboto, Arial",
    "--color-bg": "var(--bg)",
    "--color-surface": "var(--surface)",
    "--color-surface-soft": "var(--surface-2)",
    "--color-surface-muted": "#f5f5f5",
    "--color-surface-weak": "#fcfcfc",
    "--color-text": "var(--text-primary)",
    "--color-text-muted": "var(--text-secondary)",
    "--color-text-subtle": "var(--placeholder)",
    "--color-border": "var(--border)",
    "--color-border-soft": "#eeeeee",
    "--color-border-muted": "#f0f0f0",
    "--color-border-dashed": "#e1e1e1",
    "--color-divider": "var(--divider)",
    "--color-primary": "var(--accent)",
    "--color-primary-contrast": "#ffffff",
    "--color-primary-soft": "#f9fafb",
    "--color-danger-border": "#f1c4c4",
    "--color-danger-bg": "#fff5f5",
    "--color-warning": "#b45309",
    "--color-warning-border": "#ffc107",
    "--color-warning-bg": "#fff8e1",
    "--color-text-primary": "var(--text-primary)",
    "--color-text-secondary": "var(--text-secondary)",
    "--color-text-muted-alt": "var(--text-muted)",
    "--color-text-inverse": "#ffffff",
    "--color-accent": "var(--accent)",
    "--color-accent-2": "#b45309",
    "--color-focus": "var(--focus)",
    "--color-danger": "var(--danger)",
    "--color-input-bg": "var(--input-bg)",
    "--color-input-text": "var(--input-text)",
    "--color-input-border": "var(--input-border)",
    "--color-input-placeholder": "var(--placeholder)",
    "--color-button-bg": "var(--btn-bg)",
    "--color-button-text": "var(--btn-text)",
    "--color-button-border": "var(--btn-border)",
    "--color-button-secondary-bg": "#fafafa",
    "--color-button-secondary-text": "#111111",
    "--color-button-secondary-border": "#dddddd",
    "--color-overlay": "rgba(0, 0, 0, 0.5)",
    "--shadow-modal": "0 10px 30px rgba(0, 0, 0, 0.25)",
    "--shadow-toast": "0 10px 24px rgba(17, 24, 39, 0.16)",
    "--color-surface-inset": "rgba(255, 255, 255, 0.02)",
    "--color-panel-highlight": "rgba(241, 214, 173, 0.08)",
    "--color-panel-shadow": "rgba(0, 0, 0, 0.35)",
    "--font-family-base": "var(--font-ui)",
    "--font-family-mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
  },
};
